/// <reference path="../../../globals.d.ts" />

declare module goog.events {

    /**
     * Constants for event names.
     * @enum {string}
     */
    enum EventType { CLICK, DBLCLICK, MOUSEDOWN, MOUSEUP, MOUSEOVER, MOUSEOUT, MOUSEMOVE, MOUSEENTER, MOUSELEAVE, SELECTSTART, KEYPRESS, KEYDOWN, KEYUP, BLUR, FOCUS, DEACTIVATE, FOCUSIN, FOCUSOUT, CHANGE, SELECT, SUBMIT, INPUT, PROPERTYCHANGE, DRAGSTART, DRAG, DRAGENTER, DRAGOVER, DRAGLEAVE, DROP, DRAGEND, TOUCHSTART, TOUCHMOVE, TOUCHEND, TOUCHCANCEL, BEFOREUNLOAD, CONSOLEMESSAGE, CONTEXTMENU, DOMCONTENTLOADED, ERROR, HELP, LOAD, LOSECAPTURE, ORIENTATIONCHANGE, READYSTATECHANGE, RESIZE, SCROLL, UNLOAD, HASHCHANGE, PAGEHIDE, PAGESHOW, POPSTATE, COPY, PASTE, CUT, BEFORECOPY, BEFORECUT, BEFOREPASTE, ONLINE, OFFLINE, MESSAGE, CONNECT, ANIMATIONSTART, ANIMATIONEND, ANIMATIONITERATION, TRANSITIONEND, POINTERDOWN, POINTERUP, POINTERCANCEL, POINTERMOVE, POINTEROVER, POINTEROUT, POINTERENTER, POINTERLEAVE, GOTPOINTERCAPTURE, LOSTPOINTERCAPTURE, MSGESTURECHANGE, MSGESTUREEND, MSGESTUREHOLD, MSGESTURESTART, MSGESTURETAP, MSGOTPOINTERCAPTURE, MSINERTIASTART, MSLOSTPOINTERCAPTURE, MSPOINTERCANCEL, MSPOINTERDOWN, MSPOINTERENTER, MSPOINTERHOVER, MSPOINTERLEAVE, MSPOINTERMOVE, MSPOINTEROUT, MSPOINTEROVER, MSPOINTERUP, TEXTINPUT, COMPOSITIONSTART, COMPOSITIONUPDATE, COMPOSITIONEND, EXIT, LOADABORT, LOADCOMMIT, LOADREDIRECT, LOADSTART, LOADSTOP, RESPONSIVE, SIZECHANGED, UNRESPONSIVE, VISIBILITYCHANGE, STORAGE, DOMSUBTREEMODIFIED, DOMNODEINSERTED, DOMNODEREMOVED, DOMNODEREMOVEDFROMDOCUMENT, DOMNODEINSERTEDINTODOCUMENT, DOMATTRMODIFIED, DOMCHARACTERDATAMODIFIED } 
}
